config/routes.rb
Rails.application.routes.draw do
  resources :maintenance_services, only: %i[new create show]
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  ROUTE_API = 'http://127.0.0.1:3000'
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    response = RestClient.get("#{ROUTE_API}/api/v1/cars", { params: car_params.to_h })
    @cars = JSON.parse(response.body)['data']
  end

  def show
    response = RestClient.get("#{ROUTE_API}/api/v1/cars/#{car_params['id']}")
    @car = JSON.parse(response.body)
  end

  def edit
    response = RestClient.get("#{ROUTE_API}/api/v1/cars/#{car_params['id']}")
    @car = JSON.parse(response.body)
  end

  def update
    response = RestClient.patch("#{ROUTE_API}/api/v1/cars/#{car_params['id']}", car_params.to_h)
    @car = JSON.parse(response.body)

    if response.succ
      redirect_to @car, notice: 'Coche actualizado con éxito.'
    else
      render :edit
    end
  rescue StandardError => e
    puts "Se produjo un error inesperado: #{e.message}"
  end

  def create
    response = RestClient.post("#{ROUTE_API}/api/v1/cars", car_params.to_h)
    @car = JSON.parse(response.body)

    if response.succ
      redirect_to @car, notice: 'Coche creado con éxito.'
    else
      render :new
    end
  rescue StandardError => e
    puts "Se produjo un error inesperado: #{e.message}"
  end

  def destroy
    response = RestClient.delete("#{ROUTE_API}/api/v1/cars/#{car_params['id']}")
    if response.succ
      redirect_to @car, notice: 'Coche creado con éxito.'
    else
      render :new
    end
  rescue StandardError => e
    puts "Se produjo un error inesperado: #{e.message}"
  end

  def car_params
    params.permit(:id, :plate_number, :model, :year, :filter_status, :active)
  end
end

app/controllers/maintenance_services_controller.rb
class MaintenanceServicesController < ApplicationController
  def create
    response = RestClient.post("#{ROUTE_API}/api/v1/maintenance_services", maintenance_service_params.to_h)
    @service = JSON.parse(response.body)

    if response.succ
      redirect_to maintenance_service_path(id: @service['id']), notice: 'Servicio creado con éxito.'
    else
      render :new
    end
  rescue StandardError => e
    puts "Se produjo un error inesperado: #{e.message}"
  end

  def show
    response = RestClient.get("#{ROUTE_API}/api/v1/maintenance_services/#{maintenance_service_params['id']}")
    @service = JSON.parse(response.body)
  end

  def maintenance_service_params
    params.permit(:id, :description, :car_id, :status, :date, :filter_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/maintenance_service_helper.rb
module MaintenanceServiceHelper
end

app/views/cars/edit.html.erb
<h1>Edit Car <%= @car['plate_number'] %></h1>

<%= form_with(url: car_path(@car['id']), method: :patch, local: true) do |form| %>
  <div>
    <%= form.label :model, "Model" %>
    <%= form.text_field :model, value: @car['model'] %>
  </div>
  <div>
    <%= form.label :year, "Year" %>
    <%= form.number_field :year, value: @car['year'] %>
  </div>
  <div>
    <%= form.label :plate_number, "Plate number" %>
    <%= form.text_field :plate_number, value: @car['plate_number'] %>
  </div>
  <div>
    <%= form.label :active, "Is active" %>
    <%= form.text_field :active, value: @car['active'] %>
  </div>
  <br>
  <div>
    <%= form.submit "Update Car", class: "waves-effect waves-light btn" %>
  </div>
<% end %>

<%= link_to 'regresar', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>

app/views/cars/index.html.erb
<script> import Swal from 'sweetalert2' </script>

<h1>List Cars (<%= @cars.count %>)</h1>
<br>
   <%= link_to '+', new_car_path, class: "btn-floating btn-large waves-effect waves-light red" %>
 <br>
<table style="width:50%">
  <tr>
    <th style="text-align: left;">plate_number</th>
    <th style="text-align: left;">model</th>
    <th style="text-align: left;">year</th>
    <th style="text-align: left;">active</th>
    <th style="text-align: center;">actions</th>
  </tr>
  <% @cars.each do |car| %>
  <tr>
    <td><%= car['plate_number'] %></td>
     <td><%= car['model'] %></td>
     <td><%= car['year'] %></td>
     <td><%= car['active'] %></td>
     <td style="text-align: center;">
      <%= link_to 'Ver', car_path(id: car['id']), style:"color: blue; padding:5px; margin-right: 5px; cursor:pointer" %>
      <%= link_to 'Editar', edit_car_path(id: car['id']), style:"color: green; padding:5px; margin-right: 5px; cursor:pointer" %>
      <%= link_to new_maintenance_service_path(car_id: car['id']), class:'btn btn-primary', data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Add maintenance_service" do %>
        <i class="material-icons">add_circle_outline</i>
      <% end %>
      <% if car['active'] %>
        <%= link_to 'Eliminar', car_path(id: car['id']), method: :destroy, data: { confirm: '¿Estás seguro de que deseas eliminar este post?' }, class: 'btn btn-danger', style:"color: red; padding:5px; margin-right: 5px; cursor:pointer" %>
      <% end %>
     </td>
  </tr>
  <% end %>  
</table> 
<br>
<%= link_to 'ver registros activos', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>
<%= link_to 'ver registros eliminados', cars_path(filter_status: 'deleted'), style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>
<%= link_to 'ver todos los registros',  cars_path(filter_status: 'both'), style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>

app/views/cars/new.html.erb
<h1>New Car </h1>

<%= form_with(url: cars_path, method: :post, local: true) do |form| %>
  <div>
    <%= form.label :model, "Model" %>
    <%= form.text_field :model %>
  </div>
  <div>
    <%= form.label :year, "Year" %>
    <%= form.number_field :year%>
  </div>
  <div>
    <%= form.label :plate_number, "Plate number" %>
    <%= form.text_field :plate_number%>
  </div>
  <br>
  <div>
    <%= form.submit "Create Car", class: "waves-effect waves-light btn" %>
  </div>
<% end %>

<%= link_to 'regresar', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>

app/views/cars/show.html.erb
<h1>Detail car <%= @car['plate_number'] %></h1>

<ul class="collection">
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Id:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @car['id']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Plate_number:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @car['plate_number']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Model:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @car['model']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Year:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @car['year']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Is active:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @car['active']%> </p>
      </div>
    </li>
  </ul>

<h2> Maintenance Services </h2>

<table style="width:50%">
  <tr>
    <th style="text-align: left;">id</th>
    <th style="text-align: left;">description</th>
    <th style="text-align: left;">status</th>
    <th style="text-align: left;">date</th>
    <th style="text-align: center;">active</th>
  </tr>
  <% @car['maintenance_services'].each do |service| %>
    <tr>
      <td><%= service['id'] %></td>
      <td><%= service['description'] %></td>
      <td><%= service['status'] %></td>
      <td><%= service['date'] %></td>
      <td><%= service['active'] %></td>
    </tr>
  <% end %> 
</table> 

<br>
<br>
<%= link_to 'regresar', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaintenanceServiceWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  </head>

  <body>
    <%= yield %>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  
<script type="text/javascript">
  <%
=begin%>
 document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, options);
  }); 
<%
=end%>
</script>
  </body>
</html>

app/views/maintenance_services/new.html.erb
<h1>New Maintenance Service </h1>
<br>

<%= form_with(url: maintenance_services_path, method: :post, local: true) do |form| %>
  <div>
    <%= form.label :model, "Description" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :car_id, "Car id" %>
    <%= form.text_field :car_id, value: params[:car_id], readonly: true %>
  </div>
  <div>
    <%= form.label :date, "Date" %>
    <%= form.date_field :date, class: "datepicker" %>
  </div>
  <div>
    <%= form.label :status, "Status" %>
    <%= form.select :status, options_for_select([['Pending', 'pending'], ['In Progress', 'in_progress'], ['Completed', 'completed']]), { include_blank: 'Choose your option' }, { class: 'browser-default' } %>
  </div>

  <br>
  <div>
    <%= form.submit "Create Service", class: "waves-effect waves-light btn" %>
  </div>
<% end %>

<%= link_to 'regresar', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>

app/views/maintenance_services/show.html.erb
<h1>Detail Service <%= @service['id'] %></h1>

<ul class="collection">
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Id:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @service['id']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Description:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @service['description']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Status:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @service['status']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Date:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @service['date']%> </p>
      </div>
    </li>
    <li class="collection-item">
      <div style="display: flex; align-items: center;">
        <span style="font-weight: bold; font-size: 25px;", class="title">Is active:</span>
        <p style = "font-size: 25px; margin-left: 15px;"> <%= @service['active']%> </p>
      </div>
    </li>
  </ul>

<br>
<br>
<%= link_to 'regresar', cars_path, style:"color: blue; padding:50px; margin-right: 5px; cursor:pointer;" %>